# Generated by Django 5.1.1 on 2024-09-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_product_collectionimage_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='image',
            field=models.ImageField(upload_to='store/images'),
        ),
    ]
